POST http://localhost:5000/api/auth/reset-password?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGNjNjVlNzNiNmYwNDVkYjI1YjljOSIsImlhdCI6MTczMzE3NjcwMywiZXhwIjoxNzMzMTgwMzAzfQ.F8ERiFfrIIDFXqDpuKzWkXiuOjE-o2M1KJNsUZiJf5k
Content-Type: application/json

{
  "newPassword": "222222"
}
